### ISSUE TITLE
describing jsonObject elements in a jsonArray element

### ISSUE THREAD

**Issue by vsashidh** [spotify/java-hamcrest#16]
I am trying to describe the following json  structure using hamcrest-jackson: 
```
{"matches":[
             {"trials":"NCT00000001","title":"TRIALNCT00000001"},
            {"trials":"NCT00000002","title":"TRIALNCT00000002"}
       ]
 }
```
Unfortunately having trouble with it. I was able to get as far as:
```
JsonNode jsonOutput = objMapper.valueToTree(result());
assertThat(jsonOutput, is(
                jsonObject()
                        .where("matches",is(jsonArray()))
                )
        );
```
I wanted to verify that elements of the array are jsonObjects() and also match the attributes for each element in the array. How could I achieve my test desire using hamcrest-jackson?

**Comment by pettermahlen** [comment]
You should be able to use [`jsonArray(Matcher<? super Collection<JsonNode>> elementsMatcher)`](https://github.com/spotify/java-hamcrest/blob/master/jackson/src/main/java/com/spotify/hamcrest/jackson/IsJsonArray.java#L48-L51). For instance, something like this:

```java
  .where("matches", is(jsonArray(org.hamcrest.Matchers.hasSize(2))))
```
