### ISSUE TITLE
Useful additional documentation

### ISSUE THREAD

**Issue by kmbyrne** [spotify/java-hamcrest#24]
It took me a while to figure out how to use JsonArray in conjunction with contains, might be nice to add the following to the documentation:

// You can match a JSON Array by combining with existing Hamcrest collection Matchers:
String jsonArrayString = "[\"foo\", \"bar\"]";
JsonNode json = new ObjectMapper().readTree(jsonArrayString);
assertThat(json, is(JsonArray(contains(jsonText("foo"), jsonText("bar")))));

**Comment by davidxia** [comment]
Thanks for the feedback.
