### ISSUE TITLE
jsonArray does not work correctly with hasItem() or hasItems()

### ISSUE THREAD

**Issue by kmbyrne** [spotify/java-hamcrest#25]
Reproducible with the following test:

	@Test
	public void testHasItems() throws IOException
	{
		String jsonString = "[\n" +
								"  \"hello\", \"world\"\n" +
								"]";
		JsonNode json = new ObjectMapper().readTree(jsonString);
		assertThat(json, is(jsonArray(hasItem(is(jsonText("hello")))))); //this works
		assertThat(json, is(jsonArray(hasItem(is(jsonText("world")))))); //this does not
		assertThat(json, is(jsonArray(hasItems(is(jsonText("hello")))))); //this works
		assertThat(json, is(jsonArray(hasItems(is(jsonText("world")))))); //this does not
		assertThat(json, is(jsonArray(hasItems(is(jsonText("hello")), is(jsonText("world")))))); //this does not
		assertThat(json, is(jsonArray(contains(is(jsonText("hello")), is(jsonText("world")))))); //this works
	}

**Comment by eshrubs** [comment]
I just ran this locally and it works fine

**Comment by fsommar** [comment]
I got compilation errors with `com.spotify.hamcrest.jackson.JsonMatchers.jsonArray` but not with `com.spotify.hamcrest.jackson.IsJsonArray.jsonArray`. It seems that the former expects `Matcher<? super Collection<? super JsonNode>>` and the latter `Matcher<? super Collection<JsonNode>>` (which works). Is there any reason why they're not aligned?

**Comment by davidxia** [comment]
@kmbyrne I ran this locally as well, and it worked.

@fsommar It's not intentional. I think both should be `Matcher<? super Collection<? extends JsonNode>>`.

**Comment by davidxia** [comment]
@fsommar addressed in #32.
