### ISSUE TITLE
The primitive JSON matchers create weird-sounding descriptions

### ISSUE THREAD

**Issue by davidxia** [spotify/java-hamcrest#3]
For example:

    is(jsonInt(1))

...produces the description:

    is a number node is <1>

**Comment by dflemstr** [comment]
Thanks for converting this internal issue! Commenting as an easy way to get updates on this issue :)

**Comment by mattnworb** [comment]
what would be clearer? I find the `is a number node` part helpful. What about `is a number node with value <1>`? or `is a number node equal to <1>`
